[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test"
script = "script"
remappings = [
    "hardhat/=node_modules/hardhat/",
    "@arbitrum/nitro-precompiles/=lib/nitro-precompile-interfaces/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
