name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: npm ci

      - name: Start testnode
        run: npm run testnode

      - name: Run tests
        run: npm test
